version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_produtos
    ports:
      - "5433:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend-1:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/db_produtos
      INSTANCE_ID: backend-1
    depends_on:
      - postgres

  backend-2:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/db_produtos
      INSTANCE_ID: backend-2
    depends_on:
      - postgres

  gateway:
    build: ./gateway
    ports:
      - "9000:8080"
    environment:
      UPSTREAMS: http://backend-1:8000,http://backend-2:8000
      REDIS_HOST: redis
      RATE_LIMIT: 5
    depends_on:
      - backend-1
      - backend-2
      - redis

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./observability/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3030:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki